# Site settings
title: Hien Vu 
email: hienvuhuy at gmail
description: 8916-5 Takayama, Ikoma, Nara # this means to ignore newlines until "baseurl:"
 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hienvuhuy.github.io" # the base hostname & protocol for your site
twitter_username: hienvuhuy
github_username:  hienvuhuy

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Ph.D. Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
